# Generated by Django 3.2.8 on 2021-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
