# Generated by Django 3.2.8 on 2021-11-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entec', '0002_alter_game_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
